# general params
LATITUDE = 12.345
LONGITUDE = 67.890
TIMEZONE = 'Europe/Warsaw'
WEATHER_API_URL = "https://foo/bar"
PERIOD = ('month', 6)

# pvlib_predictions
SURFACE_TILT = 30
SURFACE_AZIMUTH = 180
PANEL_POWER_WATTS = 500
NUMBER_OF_PANELS = 20
INVERTER_EFFICIENCY = 0.96
PANEL_TEMPERATURE_LOSS = -0.0035

# battery storage params
BATTERY_STORAGE_CAPACITY_KILOWATTS = 5
CHARGE_EFFICIENCY = 0.95
DISCHARGE_EFFICIENCY = 0.95